### ISSUE TITLE
A question about call_hmr_ief

### ISSUE THREAD

**Issue by seamanj** [akanazawa/human_dynamics#35]
Dear author:

Thanks for your wonderful work first. I have a little question about the call_hmr_ief() function.

in this function, hmr_ief has been called three times: one for estimating the current pose, two for the past and the future. However, I just found the parameters for the current and the past are almost the same. So how can we estimate the past and the current pose with the same function and parameters? I was a little bit confused, Thanks in advance.

Regards

**Comment by akanazawa** [comment]
Hi, 

Yes a good question, it differentiates the models via scope / model name that we specify like so: 
https://github.com/akanazawa/human_dynamics/blob/2f1791ef6498d3c58159763a08662cbdda4dee93/src/models.py#L345

It requires a bit of a digging to see this, but since the content of the models are exactly the same we did not want to remake ief predictors for future / past independently. 

The model also differs in that the present model predicts the camera + shape parameter as well (so output is 85D), for future/past, the output is only pose (no camera & shape) so it's just 72D. 

Best,

Angjoo

**Comment by seamanj** [comment]
Thanks a lot. that's very helpful!
