### ISSUE TITLE
a question about read_human36m.py 

### ISSUE THREAD

**Issue by LH-Abner** [akanazawa/human_dynamics#38]
@akanazawa [https://github.com/akanazawa/human_dynamics/blob/master/src/datasets/h36/read_human36m.py]

- # Link the mp4 with the new name to the old name.
       video_paths[cam_id - 1]
        action_name = action_names[action_id - 1]
        out_video_name = 'S{}_{}_{}_cam_{}.mp4'.format(sbj_id, action_name, trial_id - 1, cam_id - 1)
        out_video_path = join(output_dir, out_video_name)
        if not exists(out_video_path):
            orig_vid_path = video_paths[cam_id - 1].replace(" ", "\ ")
            cmd = 'ln -s {} {}'.format(orig_vid_path, out_video_path)
            ret = system(cmd)
            if ret > 0:
                print('something went wrong!')
                import ipdb
                ipdb.set_trace()

I don't know what  this code can do.And I met a error when I run the read_human36m.py. the systen(cmd) can't be performed, the ret=1, have you met this question and how do you solve it ?thanks!

**Comment by akanazawa** [comment]
Hi, 

This particular code sets a consistent name for sequences from the H36M dataset. The raw data does not have consistent names (action names with different capitalization rules etc, which require you to have the xml in hand). This is so that later you can just load things from the directory without opening up the xml to figure out which camera the sequence is or something like that. It's just renaming and making a symlink as you can see.

It seems like if it's giving you ret=1, then something is wrong with the cmd on your system. This can be simple as directory not existing, no permission etc. 

I suggest, as you can see the ipdb break point there, print the cmd and run it on your shell and see what the error message says. it should be a simple symlink command like `ln -s source target`

Best of luck,

a
